spring.datasource.url=jdbc:${MYSQL_URL}

spring.application.name=habitTracker

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true